export const HANDLE_INPUT_TEXT = 'HANDLE_INPUT_TEXT'
export const RESET_INPUTS = 'RESET_INPUTS'
export const TOGGLE_READY_TO_SUBMIT = 'TOGGLE_READY_TO_SUBMIT'
export const TOGGLE_SUBMITTED = 'TOGGLE_SUBMITTED'