export const MESSAGE_CREATE_REQUEST = 'MESSAGE_CREATE_REQUEST'
export const MESSAGE_CREATE_SUCCESS = 'MESSAGE_CREATE_SUCCESS'
export const MESSAGE_CREATE_FAIL = 'MESSAGE_CREATE_FAIL'

export const HANDLE_INPUT_TEXT = 'HANDLE_INPUT_TEXT'
export const RESET_INPUTS = 'RESET_INPUTS'
export const TOGGLE_READY_TO_SUBMIT = 'TOGGLE_READY_TO_SUBMIT'
export const TOGGLE_SUBMITTED = 'TOGGLE_SUBMITTED'