export const MODAL = "MODAL";

export const MODAL_ISOPEN_REQUEST = "MODAL_ISOPEN_REQUEST";
export const MODAL_ISOPEN_SUCCESS = "MODAL_ISOPEN_SUCCESS";
export const MODAL_ISOPEN_FAIL = "MODAL_ISOPEN_FAIL";

export const MODAL_SETPROJECT_REQUEST = "MODAL_SETPROJECT_REQUEST";
export const MODAL_SETPROJECT_SUCCESS = "MODAL_SETPROJECT_SUCCESS";
export const MODAL_SETPROJECT_FAIL = "MODAL_SETPROJECT_FAIL";
export const MODAL_SETPROJECT_RESET = "MODAL_SETPROJECT_RESET";