export const MODAL = "MODAL";

export const MODAL_ISOPEN_REQUEST = "MODAL_ISOPEN_REQUEST";
export const MODAL_ISOPEN_SUCCESS = "MODAL_ISOPEN_SUCCESS";
export const MODAL_ISOPEN_FAIL = "MODAL_ISOPEN_FAIL";


